#!/bin/bash

# COUNTER_FILE="$HOME/tcred/counter/storage.txt"

# count=$(cat $COUNTER_FILE)
# count=$((count + 1))
# echo $count > $COUNTER_FILE

FILE="$HOME/tcred/counter/storage"
# Отримання поточної дати
DATE=$(date +"%Y-%m-%d")

# Ініціалізація масиву
declare -A run_counts

# Якщо файл існує, зчитуємо дані
if [ -f "$FILE" ]; then
    while IFS="=" read -r key value; do
        run_counts["$key"]=$value
    done < "$FILE"
else
    # Якщо файл не існує, створюємо його
    touch "$FILE"
fi

# Збільшуємо кількість запусків для поточної дати
if [ -n "${run_counts[$DATE]}" ]; then
    run_counts[$DATE]=$((run_counts[$DATE] + 1))
else
    run_counts[$DATE]=1
fi

# Записуємо оновлені дані у файл
> "$FILE"
for key in "${!run_counts[@]}"; do
    echo "$key=${run_counts[$key]}" >> "$FILE"
done