#!/bin/bash

# COUNTER_FILE="$HOME/tcred/counter/storage.txt"

# count=$(cat $COUNTER_FILE)
# count=$((count + 1))
# echo $count > $COUNTER_FILE

COUNTER_FILE="$HOME/tcred/counter/storage"

# Перевіряємо, чи існує файл, якщо ні - створюємо його
if [ ! -f "$COUNTER_FILE" ]; then
    touch "$COUNTER_FILE"
fi

# Ініціалізуємо асоціативний масив
declare -A counter

# Зчитуємо поточний вміст файлу у масив
while IFS="=" read -r key value; do
    counter["$key"]="$value"
done < "$COUNTER_FILE"

# Отримуємо поточну дату
current_date=$(date +"%Y-%m-%d")

# Збільшуємо лічильник для поточної дати
count=${counter["$current_date"]}
count=$((count + 1))
counter["$current_date"]=$count

# Записуємо оновлений масив у файл
> "$COUNTER_FILE"
for key in "${!counter[@]}"; do
    echo "$key=${counter[$key]}" >> "$COUNTER_FILE"
done

# Виводимо поточне значення лічильника
echo "Скрипт був запущений ${counter[$current_date]} разів на дату $current_date"